services:
  ktor:
    image:  eclipse-temurin:20-jdk
    ports:
      - "8080:8080"
    volumes:
        - $PWD:/app
    working_dir: /app
    environment:
      APP_OPTS: "-Dio.ktor.development=true -XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
    command: ./gradlew run
    restart: unless-stopped
