services:
  ktor:
    image: gradle:8.9.0-jdk11
    ports:
      - "8080:8080"
    volumes:
        - $PWD:/app
    working_dir: /app
    environment:
      APP_OPTS: "-Dio.ktor.development=true -XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
    command: [ "./gradlew", "run" ]
    restart: unless-stopped
