services:
  ktor:
    image:  eclipse-temurin:21-jdk
    ports:
      - "8080:8080"
    volumes:
        - $PWD:/app
    working_dir: /app
    command: ./gradlew run --args='-Dio.ktor.development=true'
    restart: unless-stopped
