[versions]
kotlin = "2.0.0"
ktor = "2.3.12"
junit-jupiter = "5.10.3"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.6" }

ktor-server-test = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
assertj = { module= "org.assertj:assertj-core", version = "3.26.3" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
testlogger = { id = "com.adarshr.test-logger", version = "4.0.0" }
